language: node_js

node_js:
  - "8"
  - "10"

sudo: false

matrix:
  include:
    - node_js: "10"
      env: TEST_SUITE=lint

cache:
  yarn: true

install:
  - yarn
  - chmod +x ./install-ghost.sh
  - if [ "$TEST_SUITE" != "lint" ]; then ./install-ghost.sh; fi

script:
  - if [ "$TEST_SUITE" == "lint" ]; then yarn run lint; else yarn run test:all; fi

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == "10" && "$TEST_SUITE" != "lint" ]]; then yarn run coverage; fi
